### ISSUE TITLE
Can't Compile with QMK 1.0

### ISSUE THREAD

**Issue by InvisibleFunction** [DIYCharles/MouseJiggler#1]
I'm trying to compile with QMK 1.0 but I get this:

```
(venv-qmk) me@debian:~/git/qmk_firmware$ qmk compile -kb mousejiggler -km default
Ψ Compiling keymap with gmake --jobs=1 mousejiggler:default


QMK Firmware 0.11.68
Making mousejiggler with keymap default

avr-gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/mousejiggler/mousejiggler.c                                                   In file included from keyboards/mousejiggler/mousejiggler.c:1:0:
keyboards/mousejiggler/mousejiggler.h:6:0: error: "KEYMAP" redefined [-Werror]
 #define KEYMAP( \
 ^
In file included from ./keyboards/mousejiggler/config.h:4:0,
                 from <command-line>:0:
quantum/config_common.h:28:0: note: this is the location of the previous definition
 #define KEYMAP LAYOUT
 ^
cc1: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
gmake[1]: *** [tmk_core/rules.mk:443: .build/obj_mousejiggler_default/keyboards/mousejiggler/mousejiggler.o] Error 1
gmake: *** [Makefile:539: mousejiggler:default] Error 1
Make finished with errors
(venv-qmk) me@debian:~/git/qmk_firmware$ ls keyboards/mousejiggler/
config.h  info.json  keymaps  mousejiggler.c  mousejiggler.h  rules.mk
```

any ideas?

**Comment by DIYCharles** [comment]
Make sure you are using the command line from MSYS2 64 bit. Use the cd command to get to the folder qmk_firmware. Use this command to compile
```sh
 qmk compile -kb mousejiggler/mousejiggler -km default
```

also try to update qmk to the most recent version. Try to git pull or run the command in MSYS2 64bit 
```
python3 -m pip install qmk
```

also try 
```
make git-submodule
```

**Comment by DIYCharles** [comment]
This is my output. Take note of my firmware version 0.10.50 

```sh 
Charles@DESKTOP-A02TLN6 MINGW64 /c/users/charles/qmk_firmware
$ qmk compile -kb mousejiggler/mousejiggler -km default
INFO Compiling keymap with make mousejiggler/mousejiggler:default


QMK Firmware 0.10.50
Making mousejiggler/mousejiggler with keymap default

avr-gcc.exe (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text    data     bss     dec     hex filename
      0   15936       0   15936    3e40 .build/mousejiggler_mousejiggler_default.hex

Copying mousejiggler_mousejiggler_default.hex to qmk_firmware folder                                [OK]
Checking file size of mousejiggler_mousejiggler_default.hex                                         [OK]
 * The firmware size is fine - 15936/28672 (55%, 12736 bytes free)

```

**Comment by DIYCharles** [comment]
No new info on issue closing unless you open again to add new info
